//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTuc.Models
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;
    using System.Web;

    public partial class BanTin
    {
        public static readonly string SERVER_IMG_PATH = "~/Resources/Images/News/";
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDang { get; set; }
        public string HinhAnh { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        public int MaDM { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string TKAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual DMBanTin DMBanTin { get; set; }

        public static string GetSortText(string s)
        {
            if(s.Length <= 30)
            {
                return s;
            }

            StringBuilder sb = new StringBuilder();
            for(int i = 0; i < 30; i++)
                sb.Append(s[i]);

            return sb.ToString() + "...";
        }
    }
}
