//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string UserName { get; set; }
        public int IDBanTin { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string NoiDung { get; set; }
    
        public virtual BanTin BanTin { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
