USE master;
IF EXISTS(
	SELECT *
	FROM sys.databases 
	WHERE name = N'TinTuc'
) BEGIN
	DROP DATABASE TinTuc
END;
CREATE DATABASE TinTuc;

USE TinTuc;
CREATE TABLE DMBanTin(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(30) NOT NULL,
);
CREATE TABLE Admin(
	UserName CHAR(20) NOT NULL PRIMARY KEY,
	Password VARCHAR(64) NOT NULL,
	TenAdmin NVARCHAR(50) NOT NULL
);
INSERT INTO Admin VALUES('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', N'Phạm Minh Khánh');
CREATE TABLE BanTin(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TieuDe NVARCHAR(MAX) NOT NULL,
	NoiDung NVARCHAR(MAX),
	NgayDang DATETIME NOT NULL,
	HinhAnh NVARCHAR(MAX),
	MaDM INT NOT NULL,
	SoSao INT,
	TKAdmin CHAR(20) NOT NULL,
	FOREIGN KEY (TKAdmin) REFERENCES Admin(UserName),
	FOREIGN KEY (MaDM) REFERENCES DMBanTin(ID)
);
CREATE TABLE NguoiDung(
	UserName CHAR(20) NOT NULL PRIMARY KEY,
	Password VARCHAR(64) NOT NULL,
	TenND NVARCHAR(50) NOT NULL,
	NgaySinh DATE,
	GioiTinh INT
);
CREATE TABLE Comment(
	UserName CHAR(20),
	IDBanTin INT,
	SoSao INT,
	NoiDung NVARCHAR(MAX),
	PRIMARY KEY (UserName, IDBanTin),
	FOREIGN KEY (UserName) REFERENCES NguoiDung(UserName),
	FOREIGN KEY (IDBanTin) REFERENCES BanTin(ID)
);