//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuVanDuHoc_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOSO()
        {
            this.LIENHEs = new HashSet<LIENHE>();
        }
    
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string DIACHIKH { get; set; }
        public string SDTKH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIENHE> LIENHEs { get; set; }
    }
}
