//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuVanDuHoc_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public int ID { get; set; }
        public string MAKH { get; set; }
        public string MAQG { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual HOSO HOSO { get; set; }
        public virtual QUOCGIA QUOCGIA { get; set; }
    }
}
