//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuVanDuHoc_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tuvanduhocEntities : DbContext
    {
        public tuvanduhocEntities()
            : base("name=tuvanduhocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<CHIPHI> CHIPHIs { get; set; }
        public virtual DbSet<EVENTDUHOC> EVENTDUHOCs { get; set; }
        public virtual DbSet<HOSO> HOSOes { get; set; }
        public virtual DbSet<LIENHE> LIENHEs { get; set; }
        public virtual DbSet<QUOCGIA> QUOCGIAs { get; set; }
        public virtual DbSet<TRUONGHOC> TRUONGHOCs { get; set; }
    }
}
