//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuVanDuHoc_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUONGHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRUONGHOC()
        {
            this.EVENTDUHOCs = new HashSet<EVENTDUHOC>();
        }
    
        public string MATR { get; set; }
        public string TENTR { get; set; }
        public string DIACHITR { get; set; }
        public string SDTTR { get; set; }
        public string EMAILTR { get; set; }
        public string NGDAOTAO { get; set; }
        public Nullable<double> DIEMCHUAN { get; set; }
        public Nullable<decimal> HOCPHI { get; set; }
        public string MAQG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTDUHOC> EVENTDUHOCs { get; set; }
        public virtual QUOCGIA QUOCGIA { get; set; }
    }
}
